


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE SCHEMA IF NOT EXISTS "public";


ALTER SCHEMA "public" OWNER TO "pg_database_owner";


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE OR REPLACE FUNCTION "public"."set_updated_at"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
begin
  new.updated_at = now();
  return new;
end;
$$;


ALTER FUNCTION "public"."set_updated_at"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."activities" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "lead_id" bigint,
    "activity_type" "text",
    "title" "text",
    "details" "text",
    "activity_date" "date",
    "activity_time" time without time zone,
    "customer_id" bigint
);


ALTER TABLE "public"."activities" OWNER TO "postgres";


ALTER TABLE "public"."activities" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."activities_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."customer_sites" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "customer_id" bigint NOT NULL,
    "name" "text" DEFAULT 'Primary site'::"text" NOT NULL,
    "address_line1" "text",
    "address_line2" "text",
    "city" "text",
    "postcode" "text",
    "is_primary" boolean DEFAULT false NOT NULL,
    "current_supplier" "text",
    "contract_end" "date"
);


ALTER TABLE "public"."customer_sites" OWNER TO "postgres";


COMMENT ON TABLE "public"."customer_sites" IS 'Sites/premises per customer; future home for MPANs, MPRNs, meters, contracts.';



COMMENT ON COLUMN "public"."customer_sites"."is_primary" IS 'At most one primary site per customer (enforced by partial unique index).';



ALTER TABLE "public"."customer_sites" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."customer_sites_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."customers" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "company_name" "text" NOT NULL,
    "contact_name" "text",
    "telephone" "text",
    "email" "text",
    "status" "text" DEFAULT 'Active'::"text" NOT NULL,
    "notes" "text",
    "source_lead_id" bigint
);


ALTER TABLE "public"."customers" OWNER TO "postgres";


COMMENT ON TABLE "public"."customers" IS 'Commercial energy customer accounts (book of business).';



COMMENT ON COLUMN "public"."customers"."source_lead_id" IS 'Set when converted from a lead; at most one customer per lead.';



ALTER TABLE "public"."customers" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."customers_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."leads" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "company_name" "text",
    "contact_name" "text",
    "telephone" "text",
    "email" "text",
    "supplier" "text",
    "contract_end" "date",
    "status" "text",
    "notes" "text"
);


ALTER TABLE "public"."leads" OWNER TO "postgres";


ALTER TABLE "public"."leads" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."leads_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."tasks" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "lead_id" bigint,
    "title" "text",
    "due_date" "date",
    "due_time" time without time zone,
    "priority" "text",
    "status" "text",
    "notes" "text",
    "customer_id" bigint
);


ALTER TABLE "public"."tasks" OWNER TO "postgres";


ALTER TABLE "public"."tasks" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."tasks_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."user_roles" (
    "id" "uuid" NOT NULL,
    "role" "text" DEFAULT 'read_only'::"text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "user_roles_role_check" CHECK (("role" = ANY (ARRAY['admin'::"text", 'manager'::"text", 'operations'::"text", 'consultant'::"text", 'read_only'::"text"])))
);


ALTER TABLE "public"."user_roles" OWNER TO "postgres";


ALTER TABLE ONLY "public"."activities"
    ADD CONSTRAINT "activities_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."customer_sites"
    ADD CONSTRAINT "customer_sites_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."customers"
    ADD CONSTRAINT "customers_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."customers"
    ADD CONSTRAINT "customers_source_lead_id_unique" UNIQUE ("source_lead_id");



ALTER TABLE ONLY "public"."leads"
    ADD CONSTRAINT "leads_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."tasks"
    ADD CONSTRAINT "tasks_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."user_roles"
    ADD CONSTRAINT "user_roles_pkey" PRIMARY KEY ("id");



CREATE INDEX "activities_customer_id_idx" ON "public"."activities" USING "btree" ("customer_id");



CREATE INDEX "customer_sites_contract_end_idx" ON "public"."customer_sites" USING "btree" ("contract_end");



CREATE INDEX "customer_sites_customer_id_idx" ON "public"."customer_sites" USING "btree" ("customer_id");



CREATE INDEX "customer_sites_is_primary_idx" ON "public"."customer_sites" USING "btree" ("customer_id", "is_primary");



CREATE UNIQUE INDEX "customer_sites_one_primary_per_customer" ON "public"."customer_sites" USING "btree" ("customer_id") WHERE ("is_primary" = true);



CREATE INDEX "customers_company_name_idx" ON "public"."customers" USING "btree" ("company_name");



CREATE INDEX "customers_created_at_idx" ON "public"."customers" USING "btree" ("created_at" DESC);



CREATE INDEX "customers_source_lead_id_idx" ON "public"."customers" USING "btree" ("source_lead_id") WHERE ("source_lead_id" IS NOT NULL);



CREATE INDEX "customers_status_idx" ON "public"."customers" USING "btree" ("status");



CREATE INDEX "tasks_customer_id_idx" ON "public"."tasks" USING "btree" ("customer_id");



CREATE INDEX "user_roles_role_idx" ON "public"."user_roles" USING "btree" ("role");



CREATE OR REPLACE TRIGGER "customer_sites_set_updated_at" BEFORE UPDATE ON "public"."customer_sites" FOR EACH ROW EXECUTE FUNCTION "public"."set_updated_at"();



CREATE OR REPLACE TRIGGER "customers_set_updated_at" BEFORE UPDATE ON "public"."customers" FOR EACH ROW EXECUTE FUNCTION "public"."set_updated_at"();



ALTER TABLE ONLY "public"."activities"
    ADD CONSTRAINT "activities_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "public"."customers"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."customer_sites"
    ADD CONSTRAINT "customer_sites_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "public"."customers"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."customers"
    ADD CONSTRAINT "customers_source_lead_id_fkey" FOREIGN KEY ("source_lead_id") REFERENCES "public"."leads"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."tasks"
    ADD CONSTRAINT "tasks_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "public"."customers"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."user_roles"
    ADD CONSTRAINT "user_roles_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE "public"."customer_sites" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "customer_sites_delete_anon" ON "public"."customer_sites" FOR DELETE TO "anon" USING (true);



CREATE POLICY "customer_sites_delete_authenticated" ON "public"."customer_sites" FOR DELETE TO "authenticated" USING (true);



CREATE POLICY "customer_sites_insert_anon" ON "public"."customer_sites" FOR INSERT TO "anon" WITH CHECK (true);



CREATE POLICY "customer_sites_insert_authenticated" ON "public"."customer_sites" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "customer_sites_select_anon" ON "public"."customer_sites" FOR SELECT TO "anon" USING (true);



CREATE POLICY "customer_sites_select_authenticated" ON "public"."customer_sites" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "customer_sites_update_anon" ON "public"."customer_sites" FOR UPDATE TO "anon" USING (true) WITH CHECK (true);



CREATE POLICY "customer_sites_update_authenticated" ON "public"."customer_sites" FOR UPDATE TO "authenticated" USING (true) WITH CHECK (true);



ALTER TABLE "public"."customers" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "customers_delete_anon" ON "public"."customers" FOR DELETE TO "anon" USING (true);



CREATE POLICY "customers_delete_authenticated" ON "public"."customers" FOR DELETE TO "authenticated" USING (true);



CREATE POLICY "customers_insert_anon" ON "public"."customers" FOR INSERT TO "anon" WITH CHECK (true);



CREATE POLICY "customers_insert_authenticated" ON "public"."customers" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "customers_select_anon" ON "public"."customers" FOR SELECT TO "anon" USING (true);



CREATE POLICY "customers_select_authenticated" ON "public"."customers" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "customers_update_anon" ON "public"."customers" FOR UPDATE TO "anon" USING (true) WITH CHECK (true);



CREATE POLICY "customers_update_authenticated" ON "public"."customers" FOR UPDATE TO "authenticated" USING (true) WITH CHECK (true);



ALTER TABLE "public"."user_roles" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "user_roles_admin_manage" ON "public"."user_roles" TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."user_roles" "ur"
  WHERE (("ur"."id" = "auth"."uid"()) AND ("ur"."role" = 'admin'::"text"))))) WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."user_roles" "ur"
  WHERE (("ur"."id" = "auth"."uid"()) AND ("ur"."role" = 'admin'::"text")))));



CREATE POLICY "user_roles_select_own" ON "public"."user_roles" FOR SELECT TO "authenticated" USING (("id" = "auth"."uid"()));



GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";



GRANT ALL ON FUNCTION "public"."set_updated_at"() TO "anon";
GRANT ALL ON FUNCTION "public"."set_updated_at"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."set_updated_at"() TO "service_role";



GRANT ALL ON TABLE "public"."activities" TO "anon";
GRANT ALL ON TABLE "public"."activities" TO "authenticated";
GRANT ALL ON TABLE "public"."activities" TO "service_role";



GRANT ALL ON SEQUENCE "public"."activities_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."activities_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."activities_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."customer_sites" TO "anon";
GRANT ALL ON TABLE "public"."customer_sites" TO "authenticated";
GRANT ALL ON TABLE "public"."customer_sites" TO "service_role";



GRANT ALL ON SEQUENCE "public"."customer_sites_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."customer_sites_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."customer_sites_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."customers" TO "anon";
GRANT ALL ON TABLE "public"."customers" TO "authenticated";
GRANT ALL ON TABLE "public"."customers" TO "service_role";



GRANT ALL ON SEQUENCE "public"."customers_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."customers_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."customers_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."leads" TO "anon";
GRANT ALL ON TABLE "public"."leads" TO "authenticated";
GRANT ALL ON TABLE "public"."leads" TO "service_role";



GRANT ALL ON SEQUENCE "public"."leads_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."leads_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."leads_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."tasks" TO "anon";
GRANT ALL ON TABLE "public"."tasks" TO "authenticated";
GRANT ALL ON TABLE "public"."tasks" TO "service_role";



GRANT ALL ON SEQUENCE "public"."tasks_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tasks_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tasks_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."user_roles" TO "anon";
GRANT ALL ON TABLE "public"."user_roles" TO "authenticated";
GRANT ALL ON TABLE "public"."user_roles" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";







