import { PIPELINE_STAGES, REPORT_SECTORS } from "./constants";
import type { ExecutiveReportSnapshot } from "./types";

export function getExecutiveReportSnapshot(): ExecutiveReportSnapshot {
  return {
    kpis: {
      totalCustomers: "248 (demo)",
      activeContracts: "312 (demo)",
      annualContractedSpend: "£4.82m (demo)",
      forecastCommission: "£186,400 (demo)",
      commissionReceived: "£142,800 (demo)",
      outstandingCommission: "£43,600 (demo)",
      renewalRetentionRate: "84.2% (demo)",
      quoteWinRate: "38.6% (demo)",
      liveTransferConversionRate: "61.0% (demo)",
      pipelineValue: "£1.24m (demo)",
      monthlyRevenue: "£402,000 (demo)",
      averageDealValue: "£15,480 (demo)",
    },
    sales: {
      quotesCreated: "186 (demo)",
      quotesSent: "142 (demo)",
      quotesAccepted: "58 (demo)",
      contractsWon: "47 (demo)",
      contractsLost: "11 (demo)",
      averageQuoteValue: "£81,200 (demo)",
      averageContractTerm: "34 months (demo)",
      averageSalesCycle: "28 days (demo)",
      conversionTrend: "Up 2.1 pts vs prior month (demo)",
    },
    accountManagers: [
      {
        id: "am1",
        name: "Alex Morgan (demo)",
        newLeads: "24",
        quotes: "52",
        contractsWon: "18",
        renewalsRetained: "14",
        liveTransfersHandled: "31",
        conversionRate: "42% (demo)",
        demoCommission: "£68,400",
        outstandingTasks: "6",
        performanceRank: 1,
      },
      {
        id: "am2",
        name: "Jordan Lee (demo)",
        newLeads: "19",
        quotes: "44",
        contractsWon: "15",
        renewalsRetained: "11",
        liveTransfersHandled: "28",
        conversionRate: "39% (demo)",
        demoCommission: "£54,200",
        outstandingTasks: "4",
        performanceRank: 2,
      },
      {
        id: "am3",
        name: "Sam Patel (demo)",
        newLeads: "16",
        quotes: "38",
        contractsWon: "12",
        renewalsRetained: "9",
        liveTransfersHandled: "22",
        conversionRate: "35% (demo)",
        demoCommission: "£41,800",
        outstandingTasks: "8",
        performanceRank: 3,
      },
    ],
    renewals: {
      overdue: "7 (demo)",
      due30: "18 (demo)",
      due60: "26 (demo)",
      due90: "41 (demo)",
      due6Months: "88 (demo)",
      estimatedRetainedValue: "£920,000 (demo)",
      atRiskContracts: "12 (demo)",
      retentionTrend: "Stable vs last quarter (demo)",
    },
    commission: {
      expected: "£186,400 (demo)",
      paid: "£142,800 (demo)",
      outstanding: "£43,600 (demo)",
      overdue: "£8,200 (demo)",
      disputed: "£2,400 (demo)",
      monthlyForecast: "£22,400 next month (demo)",
      supplierBreakdown: [
        { supplier: "EDF Energy (demo)", amount: "£58,400" },
        { supplier: "Opus Energy (demo)", amount: "£42,100" },
        { supplier: "British Gas Lite (demo)", amount: "£28,600" },
      ],
      managerBreakdown: [
        { manager: "Alex Morgan (demo)", amount: "£68,400" },
        { manager: "Jordan Lee (demo)", amount: "£54,200" },
        { manager: "Sam Patel (demo)", amount: "£41,800" },
      ],
    },
    pipeline: PIPELINE_STAGES.map((stage, index) => ({
      stage,
      count: `${40 - index * 5} (demo)`,
      estimatedValue: `£${(200 - index * 22).toLocaleString("en-GB")}k (demo)`,
      conversionToNext: index < 5 ? `${72 - index * 8}% (demo)` : "—",
      avgDaysInStage: `${4 + index * 2} days (demo)`,
      bottleneck: stage === "Quoted" ? "Yes (demo)" : "No",
    })),
    customers: {
      largestCustomers: [
        "Derby Manufacturing Ltd — £109k spend (demo)",
        "Beacon Health Trust — £142k spend (demo)",
        "Meridian Labs — £102k spend (demo)",
      ],
      mostProfitable: [
        "Northbridge Care — £3,960 commission (demo)",
        "Derby Manufacturing — £4,860 commission (demo)",
      ],
      atRisk: ["Atlas Metals — expired (demo)", "Greenleaf Hotels — lost (demo)"],
      recentlyAdded: ["Northbridge Care (Jul 2026 demo)", "Civic Workspace Ltd (demo)"],
      noRecentContact: ["Summit Print Co (demo)", "Oakwood Estates (demo)"],
      missingData: ["4 customers missing LOA (demo)", "2 missing meter data (demo)"],
      multiSite: ["Derby Manufacturing Ltd (demo)", "Peak Logistics Group (demo)"],
      avgLtvPlaceholder: "Not configured — demo placeholder only",
    },
    sectors: REPORT_SECTORS.map((sector, i) => ({
      sector,
      customerCount: `${18 + (i % 5) * 3} (demo)`,
      annualConsumption: `${120 + i * 15}k MWh (demo)`,
      contractValue: `£${(80 + i * 12).toLocaleString("en-GB")}k (demo)`,
      quoteWinRate: `${32 + (i % 4) * 3}% (demo)`,
      renewalRetention: `${78 + (i % 3) * 4}% (demo)`,
      demoCommission: `£${(8 + i * 1.2).toFixed(1)}k (demo)`,
    })),
    suppliers: [
      {
        supplier: "EDF Energy (demo)",
        quotes: "48",
        wins: "19",
        acceptanceRate: "62% (demo)",
        turnaround: "2.4 days (demo)",
        commissionPaid: "£98,400",
        commissionOutstanding: "£25,600",
        avgPaymentDays: "45 (demo)",
        serviceRating: "4.2/5 (demo)",
        risk: "Low (demo)",
      },
      {
        supplier: "Opus Energy (demo)",
        quotes: "62",
        wins: "15",
        acceptanceRate: "58% (demo)",
        turnaround: "1.8 days (demo)",
        commissionPaid: "£72,100",
        commissionOutstanding: "£14,100",
        avgPaymentDays: "52 (demo)",
        serviceRating: "3.9/5 (demo)",
        risk: "Medium (demo)",
      },
    ],
    liveTransfers: {
      transfersReceived: "142 (demo)",
      transfersQualified: "118 (demo)",
      transfersConverted: "72 (demo)",
      avgWaitTime: "00:03:48 (demo)",
      conversionByAgent: [
        { agent: "Jordan Lee (demo)", rate: "64% (demo)" },
        { agent: "Alex Morgan (demo)", rate: "59% (demo)" },
      ],
      conversionBySource: [
        { source: "Inbound renewal line (demo)", rate: "58% (demo)" },
        { source: "Web callback (demo)", rate: "52% (demo)" },
      ],
      demoRevenue: "£18,400 influenced (demo)",
      lostReasons: ["No answer (demo)", "Wrong department (demo)", "Price objection (demo)"],
    },
    trends: [
      {
        id: "monthly-sales",
        title: "Monthly sales (demo index)",
        points: [
          { label: "Jan", value: 62, display: "62" },
          { label: "Feb", value: 58, display: "58" },
          { label: "Mar", value: 71, display: "71" },
          { label: "Apr", value: 68, display: "68" },
          { label: "May", value: 74, display: "74" },
          { label: "Jun", value: 79, display: "79" },
          { label: "Jul", value: 82, display: "82" },
        ],
      },
      {
        id: "monthly-commission",
        title: "Monthly commission (demo index)",
        points: [
          { label: "Jan", value: 55, display: "55" },
          { label: "Feb", value: 52, display: "52" },
          { label: "Mar", value: 61, display: "61" },
          { label: "Apr", value: 64, display: "64" },
          { label: "May", value: 70, display: "70" },
          { label: "Jun", value: 73, display: "73" },
          { label: "Jul", value: 76, display: "76" },
        ],
      },
      {
        id: "renewal-pipeline",
        title: "Renewal pipeline (demo)",
        points: [
          { label: "Overdue", value: 12, display: "12" },
          { label: "30d", value: 28, display: "28" },
          { label: "60d", value: 35, display: "35" },
          { label: "90d", value: 42, display: "42" },
        ],
      },
      {
        id: "quote-conversion",
        title: "Quote conversion (demo)",
        points: [
          { label: "Sent", value: 100, display: "100%" },
          { label: "Viewed", value: 72, display: "72%" },
          { label: "Accepted", value: 39, display: "39%" },
        ],
      },
      {
        id: "supplier-perf",
        title: "Supplier wins (demo)",
        points: [
          { label: "EDF", value: 80, display: "19 wins" },
          { label: "Opus", value: 65, display: "15 wins" },
          { label: "BGL", value: 40, display: "9 wins" },
        ],
      },
      {
        id: "live-transfer",
        title: "Live transfer conversion (demo)",
        points: [
          { label: "Wk1", value: 58, display: "58%" },
          { label: "Wk2", value: 61, display: "61%" },
          { label: "Wk3", value: 59, display: "59%" },
          { label: "Wk4", value: 64, display: "64%" },
        ],
      },
      {
        id: "customer-growth",
        title: "Customer growth (demo)",
        points: [
          { label: "Q1", value: 45, display: "+12" },
          { label: "Q2", value: 52, display: "+14" },
          { label: "Q3", value: 48, display: "+11" },
        ],
      },
      {
        id: "sector-mix",
        title: "Sector mix — manufacturing share (demo)",
        points: [
          { label: "Mfg", value: 78, display: "28%" },
          { label: "Retail", value: 55, display: "18%" },
          { label: "Care", value: 42, display: "14%" },
        ],
      },
    ],
    alerts: [
      { id: "a1", category: "Overdue commission", message: "£8,200 overdue (demo)", severity: "high" },
      { id: "a2", category: "Renewals requiring action", message: "18 due within 30 days (demo)", severity: "high" },
      { id: "a3", category: "Quotes close to expiry", message: "6 quotes expiring (demo)", severity: "medium" },
      { id: "a4", category: "Contracts missing paperwork", message: "4 LOAs pending (demo)", severity: "medium" },
      { id: "a5", category: "Customers without recent contact", message: "9 accounts (demo)", severity: "medium" },
      { id: "a6", category: "Suppliers requiring review", message: "2 suppliers (demo)", severity: "low" },
      { id: "a7", category: "Tasks overdue", message: "11 tasks (demo)", severity: "high" },
      { id: "a8", category: "Data quality issues", message: "Missing meter data on 2 sites (demo)", severity: "low" },
    ],
    aiInsights: [
      {
        id: "ai1",
        title: "Manufacturing renewals are increasing",
        detail: "Demo: +14% renewal volume in manufacturing sector vs last month.",
      },
      {
        id: "ai2",
        title: "Hospitality quote conversion has fallen",
        detail: "Demo: conversion down 3.2 pts — review pricing pack.",
      },
      {
        id: "ai3",
        title: "One supplier has slower payment performance",
        detail: "Demo: SmartestEnergy average payment 61 days.",
      },
      {
        id: "ai4",
        title: "Several high-value renewals require attention",
        detail: "Demo: 4 contracts above £100k EACV in 30-day window.",
      },
      {
        id: "ai5",
        title: "Live transfer wait time is above target",
        detail: "Demo: 3:48 average vs 3:00 target.",
      },
      {
        id: "ai6",
        title: "Commission exposure is increasing",
        detail: "Demo: outstanding up £4.2k vs prior month.",
      },
      {
        id: "ai7",
        title: "Strong conversion trend",
        detail: "Demo: Alex Morgan +4 pts conversion vs team average.",
      },
      {
        id: "ai8",
        title: "Data quality affecting reporting accuracy",
        detail: "Demo: 2 customers missing half-hourly feeds.",
      },
    ],
  };
}
