import type { RenewalUrgency } from "../../intelligence/types";
import type { RecommendationVerdict } from "./decisionTypes";

/**
 * Maps evidence to one of a fixed, closed set of recommendation verdicts.
 * The recommendation is always drawn from this vocabulary — never
 * free-form text, never generated by a model. This is deliberately the
 * opposite of a fabricated, arbitrary decision string.
 */
export function deriveRecommendationVerdict(
  renewalStatus: "ok" | "insufficient_data" | "not_configured" | "pending_approval" | "unavailable" | "error" | undefined,
  urgency: RenewalUrgency | undefined,
  missingDataCount: number,
): RecommendationVerdict {
  if (renewalStatus !== "ok") {
    return "Recommendation unavailable — insufficient data";
  }

  if (urgency === "Overdue") {
    return "Recommend immediate review (overdue)";
  }

  if (urgency === "Critical" || urgency === "Urgent") {
    return "Recommend tender preparation";
  }

  if (missingDataCount > 0) {
    return "Recommend confirming missing information";
  }

  return "Recommend qualification call";
}
