import type { DemoSupplierAiRecommendation, DemoSupplierRecord, Sector, SectorAppetiteLevel } from "./types";

function sectorMap(
  overrides: Partial<Record<Sector, SectorAppetiteLevel>> = {},
): Record<Sector, SectorAppetiteLevel> {
  const sectors: Sector[] = [
    "Hospitality",
    "Manufacturing",
    "Retail",
    "Warehousing",
    "Offices",
    "Care",
    "Education",
    "Leisure",
    "Food production",
    "Automotive",
    "Property management",
    "Multi-site portfolios",
  ];

  return sectors.reduce(
    (acc, sector) => {
      acc[sector] = overrides[sector] ?? "Selective";
      return acc;
    },
    {} as Record<Sector, SectorAppetiteLevel>,
  );
}

function perf(partial: Partial<DemoSupplierRecord["performance"]> = {}): DemoSupplierRecord["performance"] {
  return {
    quotesSubmitted: "48 (demo)",
    quotesReturned: "44 (demo)",
    quotesAccepted: "18 (demo)",
    contractsSubmitted: "22 (demo)",
    contractsLive: "19 (demo)",
    contractsRejected: "3 (demo)",
    renewalsRetained: "85% (demo)",
    renewalsLost: "15% (demo)",
    avgContractTerm: "36 months (demo)",
    avgAnnualConsumption: "420,000 kWh (demo)",
    complaintLevel: "Low (demo)",
    renewalSuccess: "82% (demo)",
    paymentSpeedScore: "78/100 (demo)",
    ...partial,
  };
}

export function getDemoSuppliers(): DemoSupplierRecord[] {
  return [
    {
      id: "sup-edf",
      name: "EDF Energy (demo)",
      category: "Major supplier (demo)",
      status: "Preferred",
      preferred: true,
      electricityAvailable: true,
      gasAvailable: true,
      smeAppetite: "Selective (demo)",
      corporateAppetite: "Strong (demo)",
      multiSiteAppetite: "Strong (demo)",
      renewableOptions: "REGO-backed (demo)",
      avgQuoteTurnaround: "2.4 days (demo)",
      quoteAcceptanceRate: "62% (demo)",
      contractSuccessRate: "88% (demo)",
      avgCommissionRate: "3.2% (demo)",
      avgPaymentDays: "45 days (demo)",
      serviceRating: "4.2 / 5 (demo)",
      riskRating: "Low",
      lastReviewed: "15 Jul 2026 (demo)",
      marketSegment: "Corporate",
      preferredSectors: "Manufacturing, Multi-site (demo)",
      winRate: "41% (demo)",
      openDisputes: "1 (demo)",
      accountOwner: "Alex Morgan (demo)",
      fuelFilter: "Dual",
      sectorAppetite: sectorMap({
        Manufacturing: "Strong appetite",
        "Multi-site portfolios": "Strong appetite",
      }),
      performance: perf(),
      commission: {
        expectedCommission: "£124,000 (demo)",
        paidCommission: "£98,400 (demo)",
        outstandingCommission: "£25,600 (demo)",
        avgPaymentDays: "45 (demo)",
        latePayments: "2 (demo)",
        disputedCommission: "£1,200 (demo)",
        reconciliationRequired: "1 case (demo)",
        commissionRiskLevel: "Low",
      },
      service: {
        accountManager: "Demo Desk — North (demo)",
        escalationContact: "escalation.demo@edf.example",
        quoteDesk: "quotes.demo@edf.example",
        contractSupport: "contracts.demo@edf.example",
        meteringSupport: "metering.demo@edf.example",
        complaintsContact: "complaints.demo@edf.example",
        avgResponseTime: "4.2 hrs (demo)",
        lastServiceIssue: "12 Jul 2026 — HH delay (demo)",
        openServiceCases: "2 (demo)",
      },
      notes: {
        internalNotes: "Preferred for industrial HH — demo note.",
        lastReview: "15 Jul 2026 (demo)",
        reviewedBy: "Alex Morgan (demo)",
        nextReview: "15 Oct 2026 (demo)",
        serviceConcerns: "Occasional HH file delays (demo)",
        pricingConcerns: "None flagged (demo)",
        commissionConcerns: "Minor reconciliation (demo)",
        appetiteChanges: "Stable (demo)",
        recommendedAction: "Maintain preferred status (demo)",
      },
    },
    {
      id: "sup-opus",
      name: "Opus Energy (demo)",
      category: "Independent (demo)",
      status: "Active",
      preferred: false,
      electricityAvailable: true,
      gasAvailable: true,
      smeAppetite: "Strong (demo)",
      corporateAppetite: "Selective (demo)",
      multiSiteAppetite: "Selective (demo)",
      renewableOptions: "Limited REGO (demo)",
      avgQuoteTurnaround: "1.8 days (demo)",
      quoteAcceptanceRate: "58% (demo)",
      contractSuccessRate: "81% (demo)",
      avgCommissionRate: "2.9% (demo)",
      avgPaymentDays: "52 days (demo)",
      serviceRating: "3.9 / 5 (demo)",
      riskRating: "Medium",
      lastReviewed: "10 Jul 2026 (demo)",
      marketSegment: "SME",
      preferredSectors: "Retail, Offices (demo)",
      winRate: "36% (demo)",
      openDisputes: "0 (demo)",
      accountOwner: "Jordan Lee (demo)",
      fuelFilter: "Dual",
      sectorAppetite: sectorMap({ Retail: "Strong appetite", Offices: "Strong appetite" }),
      performance: perf({ quotesSubmitted: "62 (demo)", quotesAccepted: "22 (demo)" }),
      commission: {
        expectedCommission: "£86,200 (demo)",
        paidCommission: "£72,100 (demo)",
        outstandingCommission: "£14,100 (demo)",
        avgPaymentDays: "52 (demo)",
        latePayments: "4 (demo)",
        disputedCommission: "£0 (demo)",
        reconciliationRequired: "0 (demo)",
        commissionRiskLevel: "Medium",
      },
      service: {
        accountManager: "Demo SME Team (demo)",
        escalationContact: "escalation.demo@opus.example",
        quoteDesk: "quotes.demo@opus.example",
        contractSupport: "contracts.demo@opus.example",
        meteringSupport: "Not configured (demo)",
        complaintsContact: "complaints.demo@opus.example",
        avgResponseTime: "6.1 hrs (demo)",
        lastServiceIssue: "05 Jul 2026 — quote SLA (demo)",
        openServiceCases: "1 (demo)",
      },
      notes: {
        internalNotes: "Fast quotes for SME — demo.",
        lastReview: "10 Jul 2026 (demo)",
        reviewedBy: "Jordan Lee (demo)",
        nextReview: "10 Oct 2026 (demo)",
        serviceConcerns: "Quote desk SLA watch (demo)",
        pricingConcerns: "Competitive on SME (demo)",
        commissionConcerns: "Payment slightly slow (demo)",
        appetiteChanges: "Retail appetite up (demo)",
        recommendedAction: "Monitor payment performance (demo)",
      },
    },
    {
      id: "sup-bgl",
      name: "British Gas Lite (demo)",
      category: "Major supplier (demo)",
      status: "Active",
      preferred: false,
      electricityAvailable: false,
      gasAvailable: true,
      smeAppetite: "Strong (demo)",
      corporateAppetite: "Limited (demo)",
      multiSiteAppetite: "Limited (demo)",
      renewableOptions: "Biomethane option (demo)",
      avgQuoteTurnaround: "3.1 days (demo)",
      quoteAcceptanceRate: "54% (demo)",
      contractSuccessRate: "76% (demo)",
      avgCommissionRate: "2.6% (demo)",
      avgPaymentDays: "48 days (demo)",
      serviceRating: "3.7 / 5 (demo)",
      riskRating: "Medium",
      lastReviewed: "08 Jul 2026 (demo)",
      marketSegment: "SME",
      preferredSectors: "Care, Hospitality (demo)",
      winRate: "32% (demo)",
      openDisputes: "2 (demo)",
      accountOwner: "Sam Patel (demo)",
      fuelFilter: "Gas",
      sectorAppetite: sectorMap({ Care: "Strong appetite", Hospitality: "Selective" }),
      performance: perf({ complaintLevel: "Medium (demo)" }),
      commission: {
        expectedCommission: "£64,800 (demo)",
        paidCommission: "£58,200 (demo)",
        outstandingCommission: "£6,600 (demo)",
        avgPaymentDays: "48 (demo)",
        latePayments: "1 (demo)",
        disputedCommission: "£800 (demo)",
        reconciliationRequired: "1 case (demo)",
        commissionRiskLevel: "Medium",
      },
      service: {
        accountManager: "Demo Gas Desk (demo)",
        escalationContact: "escalation.demo@bglite.example",
        quoteDesk: "quotes.demo@bglite.example",
        contractSupport: "contracts.demo@bglite.example",
        meteringSupport: "metering.demo@bglite.example",
        complaintsContact: "complaints.demo@bglite.example",
        avgResponseTime: "5.5 hrs (demo)",
        lastServiceIssue: "01 Jul 2026 — billing query (demo)",
        openServiceCases: "3 (demo)",
      },
      notes: {
        internalNotes: "Gas-only positioning — demo.",
        lastReview: "08 Jul 2026 (demo)",
        reviewedBy: "Sam Patel (demo)",
        nextReview: "08 Oct 2026 (demo)",
        serviceConcerns: "Complaint volume elevated (demo)",
        pricingConcerns: "Watch winter gas (demo)",
        commissionConcerns: "Low dispute value (demo)",
        appetiteChanges: "Care sector stable (demo)",
        recommendedAction: "Supplier service review required (demo)",
      },
    },
    {
      id: "sup-smart",
      name: "SmartestEnergy (demo)",
      category: "Independent (demo)",
      status: "Under review",
      preferred: false,
      electricityAvailable: true,
      gasAvailable: false,
      smeAppetite: "Limited (demo)",
      corporateAppetite: "Strong (demo)",
      multiSiteAppetite: "Selective (demo)",
      renewableOptions: "100% renewable tariffs (demo)",
      avgQuoteTurnaround: "2.9 days (demo)",
      quoteAcceptanceRate: "49% (demo)",
      contractSuccessRate: "74% (demo)",
      avgCommissionRate: "3.0% (demo)",
      avgPaymentDays: "61 days (demo)",
      serviceRating: "3.5 / 5 (demo)",
      riskRating: "High",
      lastReviewed: "20 Jun 2026 (demo)",
      marketSegment: "Industrial",
      preferredSectors: "Manufacturing, Food production (demo)",
      winRate: "28% (demo)",
      openDisputes: "3 (demo)",
      accountOwner: "Alex Morgan (demo)",
      fuelFilter: "Electricity",
      sectorAppetite: sectorMap({
        Manufacturing: "Strong appetite",
        "Food production": "Selective",
        Education: "Limited",
      }),
      performance: perf({
        renewalsLost: "22% (demo)",
        paymentSpeedScore: "62/100 (demo)",
      }),
      commission: {
        expectedCommission: "£92,400 (demo)",
        paidCommission: "£71,000 (demo)",
        outstandingCommission: "£21,400 (demo)",
        avgPaymentDays: "61 (demo)",
        latePayments: "6 (demo)",
        disputedCommission: "£2,400 (demo)",
        reconciliationRequired: "2 cases (demo)",
        commissionRiskLevel: "High",
      },
      service: {
        accountManager: "Demo Industrial Team (demo)",
        escalationContact: "escalation.demo@smartest.example",
        quoteDesk: "quotes.demo@smartest.example",
        contractSupport: "contracts.demo@smartest.example",
        meteringSupport: "metering.demo@smartest.example",
        complaintsContact: "complaints.demo@smartest.example",
        avgResponseTime: "7.8 hrs (demo)",
        lastServiceIssue: "18 Jun 2026 — payment delay (demo)",
        openServiceCases: "4 (demo)",
      },
      notes: {
        internalNotes: "Payment performance deteriorating — demo flag.",
        lastReview: "20 Jun 2026 (demo)",
        reviewedBy: "Alex Morgan (demo)",
        nextReview: "20 Aug 2026 (demo)",
        serviceConcerns: "Escalations increasing (demo)",
        pricingConcerns: "Renewable premium (demo)",
        commissionConcerns: "Late payments cluster (demo)",
        appetiteChanges: "Limited appetite this month (demo)",
        recommendedAction: "Commission review required (demo)",
      },
    },
    {
      id: "sup-total",
      name: "TotalEnergies (demo)",
      category: "Major supplier (demo)",
      status: "Limited appetite",
      preferred: false,
      electricityAvailable: true,
      gasAvailable: true,
      smeAppetite: "Not currently available (demo)",
      corporateAppetite: "Selective (demo)",
      multiSiteAppetite: "Strong (demo)",
      renewableOptions: "PPA options (demo)",
      avgQuoteTurnaround: "4.2 days (demo)",
      quoteAcceptanceRate: "45% (demo)",
      contractSuccessRate: "70% (demo)",
      avgCommissionRate: "2.8% (demo)",
      avgPaymentDays: "55 days (demo)",
      serviceRating: "3.6 / 5 (demo)",
      riskRating: "Medium",
      lastReviewed: "12 Jul 2026 (demo)",
      marketSegment: "Corporate",
      preferredSectors: "Multi-site portfolios (demo)",
      winRate: "25% (demo)",
      openDisputes: "1 (demo)",
      accountOwner: "Jordan Lee (demo)",
      fuelFilter: "Dual",
      sectorAppetite: sectorMap({
        "Multi-site portfolios": "Strong appetite",
        Warehousing: "Selective",
        Hospitality: "Not currently available",
      }),
      performance: perf({ quotesSubmitted: "28 (demo)" }),
      commission: {
        expectedCommission: "£58,000 (demo)",
        paidCommission: "£52,400 (demo)",
        outstandingCommission: "£5,600 (demo)",
        avgPaymentDays: "55 (demo)",
        latePayments: "2 (demo)",
        disputedCommission: "£0 (demo)",
        reconciliationRequired: "0 (demo)",
        commissionRiskLevel: "Medium",
      },
      service: {
        accountManager: "Demo Corporate Team (demo)",
        escalationContact: "escalation.demo@total.example",
        quoteDesk: "quotes.demo@total.example",
        contractSupport: "contracts.demo@total.example",
        meteringSupport: "Not configured (demo)",
        complaintsContact: "complaints.demo@total.example",
        avgResponseTime: "8.2 hrs (demo)",
        lastServiceIssue: "None this month (demo)",
        openServiceCases: "0 (demo)",
      },
      notes: {
        internalNotes: "Suitable for large multi-site — demo guidance.",
        lastReview: "12 Jul 2026 (demo)",
        reviewedBy: "Jordan Lee (demo)",
        nextReview: "12 Nov 2026 (demo)",
        serviceConcerns: "Slow quote desk (demo)",
        pricingConcerns: "Corporate-only bands (demo)",
        commissionConcerns: "Stable (demo)",
        appetiteChanges: "SME closed (demo)",
        recommendedAction: "Avoid for low-consumption SME (demo)",
      },
    },
    {
      id: "sup-sse",
      name: "SSE Business Energy (demo)",
      category: "Major supplier (demo)",
      status: "Temporarily unavailable",
      preferred: false,
      electricityAvailable: true,
      gasAvailable: true,
      smeAppetite: "Limited (demo)",
      corporateAppetite: "Selective (demo)",
      multiSiteAppetite: "Limited (demo)",
      renewableOptions: "Standard mix (demo)",
      avgQuoteTurnaround: "— (demo)",
      quoteAcceptanceRate: "— (demo)",
      contractSuccessRate: "— (demo)",
      avgCommissionRate: "2.5% (demo)",
      avgPaymentDays: "50 days (demo)",
      serviceRating: "3.4 / 5 (demo)",
      riskRating: "Critical",
      lastReviewed: "01 Jul 2026 (demo)",
      marketSegment: "Public sector",
      preferredSectors: "Education, Care (demo)",
      winRate: "— (demo)",
      openDisputes: "0 (demo)",
      accountOwner: "Sam Patel (demo)",
      fuelFilter: "Dual",
      sectorAppetite: sectorMap({
        Education: "Strong appetite",
        Care: "Selective",
        Manufacturing: "Not currently available",
      }),
      performance: perf({
        quotesSubmitted: "0 (demo)",
        quotesReturned: "0 (demo)",
        quotesAccepted: "0 (demo)",
      }),
      commission: {
        expectedCommission: "£12,000 (demo)",
        paidCommission: "£12,000 (demo)",
        outstandingCommission: "£0 (demo)",
        avgPaymentDays: "50 (demo)",
        latePayments: "0 (demo)",
        disputedCommission: "£0 (demo)",
        reconciliationRequired: "0 (demo)",
        commissionRiskLevel: "Low",
      },
      service: {
        accountManager: "Unavailable (demo)",
        escalationContact: "Not configured (demo)",
        quoteDesk: "Paused (demo)",
        contractSupport: "contracts.demo@sse.example",
        meteringSupport: "Not configured (demo)",
        complaintsContact: "complaints.demo@sse.example",
        avgResponseTime: "— (demo)",
        lastServiceIssue: "Pricing pause announced (demo)",
        openServiceCases: "0 (demo)",
      },
      notes: {
        internalNotes: "Temporarily unavailable for new quotes — demo.",
        lastReview: "01 Jul 2026 (demo)",
        reviewedBy: "Sam Patel (demo)",
        nextReview: "01 Sep 2026 (demo)",
        serviceConcerns: "Quote desk paused (demo)",
        pricingConcerns: "Portfolio review (demo)",
        commissionConcerns: "None (demo)",
        appetiteChanges: "Limited appetite this month (demo)",
        recommendedAction: "Do not tender until reopened (demo)",
      },
    },
  ];
}

export function getDemoSupplierAiRecommendations(): DemoSupplierAiRecommendation[] {
  return [
    {
      id: "ai-s1",
      title: "Best supplier for this sector",
      detail: "EDF Energy — strongest manufacturing appetite in demo register.",
      supplierId: "sup-edf",
    },
    {
      id: "ai-s2",
      title: "Strongest acceptance rate",
      detail: "EDF Energy — 62% demo acceptance vs portfolio average.",
      supplierId: "sup-edf",
    },
    {
      id: "ai-s3",
      title: "Fastest quote turnaround",
      detail: "Opus Energy — 1.8 days average in demo data.",
      supplierId: "sup-opus",
    },
    {
      id: "ai-s4",
      title: "Lowest commission risk",
      detail: "EDF Energy — low commission risk band (demo).",
      supplierId: "sup-edf",
    },
    {
      id: "ai-s5",
      title: "Avoid for low-consumption SME",
      detail: "TotalEnergies — SME appetite not available (demo).",
      supplierId: "sup-total",
    },
    {
      id: "ai-s6",
      title: "Suitable for large multi-site portfolio",
      detail: "TotalEnergies — strong multi-site appetite (demo).",
      supplierId: "sup-total",
    },
    {
      id: "ai-s7",
      title: "Renewable option available",
      detail: "SmartestEnergy — 100% renewable tariffs (demo).",
      supplierId: "sup-smart",
    },
    {
      id: "ai-s8",
      title: "Supplier service review required",
      detail: "British Gas Lite — elevated complaints in demo panel.",
      supplierId: "sup-bgl",
    },
    {
      id: "ai-s9",
      title: "Payment performance deteriorating",
      detail: "SmartestEnergy — 61 day average payment (demo).",
      supplierId: "sup-smart",
    },
    {
      id: "ai-s10",
      title: "Limited appetite this month",
      detail: "SSE Business Energy — temporarily unavailable (demo).",
      supplierId: "sup-sse",
    },
  ];
}
