import { createCorrelationId } from "@/lib/workflows/correlation";

import { CONTEXT_VERSION, RULE_VERSION } from "./constants";
import { priorityLabelFromScore } from "./scoring";
import type { DecisionContext, Recommendation } from "./types";

function ukLabel(iso: string): string {
  const d = new Date(iso);
  return new Intl.DateTimeFormat("en-GB", { dateStyle: "short", timeStyle: "short", timeZone: "Europe/London" }).format(d);
}

const DEMO_CORR = createCorrelationId("DECISION-001");
const NOW = "2026-07-28T16:00:00.000Z";

function rec(partial: Omit<Recommendation, "demonstration" | "correlationId" | "createdDate" | "createdLabel" | "updatedDate" | "updatedLabel"> & { priorityScore: number }): Recommendation {
  return {
    ...partial,
    correlationId: DEMO_CORR,
    createdDate: NOW,
    createdLabel: ukLabel(NOW),
    updatedDate: NOW,
    updatedLabel: ukLabel(NOW),
    demonstration: true,
  };
}

export function buildRecommendationsFromContext(
  ctx: DecisionContext,
  priorityScore: number,
  approvalRequired: boolean,
): Recommendation[] {
  const customer = ctx.customerId ?? "CUST-DEMO-001";
  const priority = priorityLabelFromScore(priorityScore);
  return [
    rec({
      id: "REC-DEMO-001",
      title: "Call Derby Manufacturing today",
      description: "Critical renewal contact overdue (demo).",
      businessArea: "Renewals",
      recordType: "Customer",
      recordId: customer,
      customerId: customer,
      siteId: "SITE-DEMO-01",
      opportunityType: "Renewal retention",
      recommendedAction: "Call customer",
      priority,
      priorityScore,
      risk: "High",
      confidence: "Medium confidence (demo)",
      estimatedDemoRevenueImpact: "£109k ACV (demo)",
      estimatedDemoRevenueAtRisk: "£42k margin (demo)",
      evidence: [{ id: "ev1", source: "Workflow event", summary: "Renewal window opened", module: "Renewals", demonstration: true }],
      explanation: "Priority from expiry proximity and value (demo).",
      owner: "Alex Morgan (demo)",
      dueDate: "2026-07-28",
      dueDateLabel: "28 Jul 2026",
      humanApprovalRequired: approvalRequired,
      sourceEvents: ["Renewal window opened"],
      status: "New",
    }),
    rec({
      id: "REC-DEMO-002",
      title: "Start renewal tender",
      description: "High consumption — tender recommended (demo).",
      businessArea: "Renewals",
      recordType: "Customer",
      recordId: customer,
      customerId: customer,
      siteId: null,
      opportunityType: "Renewal retention",
      recommendedAction: "Start tender",
      priority: "High",
      priorityScore: priorityScore - 5,
      risk: "Medium",
      confidence: "Medium confidence (demo)",
      estimatedDemoRevenueImpact: "£85k (demo)",
      estimatedDemoRevenueAtRisk: "£12k (demo)",
      evidence: [{ id: "ev2", source: "Consumption", summary: "600k kWh combined", module: "Customer 360", demonstration: true }],
      explanation: "Consumption threshold matched (demo).",
      owner: "Sam Patel (demo)",
      dueDate: "2026-07-29",
      dueDateLabel: "29 Jul 2026",
      humanApprovalRequired: false,
      sourceEvents: ["Consumption updated"],
      status: "Under review",
    }),
    rec({
      id: "REC-DEMO-003",
      title: "Chase overdue commission",
      description: "Supplier payment delayed (demo).",
      businessArea: "Commission",
      recordType: "Commission",
      recordId: "COM-DEMO-772",
      customerId: "CUST-DEMO-002",
      siteId: null,
      opportunityType: "Commission recovery",
      recommendedAction: "Chase supplier",
      priority: "High",
      priorityScore: 78,
      risk: "Medium",
      confidence: "Medium confidence (demo)",
      estimatedDemoRevenueImpact: "£8.2k recovery (demo)",
      estimatedDemoRevenueAtRisk: "£8.2k (demo)",
      evidence: [{ id: "ev3", source: "Commission register", summary: "14 days overdue", module: "Commission Intelligence", demonstration: true }],
      explanation: "Commission overdue rule (demo).",
      owner: "Alex Morgan (demo)",
      dueDate: "2026-07-28",
      dueDateLabel: "28 Jul 2026",
      humanApprovalRequired: true,
      sourceEvents: ["Commission overdue"],
      status: "New",
    }),
    rec({
      id: "REC-DEMO-004",
      title: "Correct missing MPAN",
      description: "Data completeness blocker (demo).",
      businessArea: "Operations",
      recordType: "Site",
      recordId: "SITE-DEMO-02",
      customerId: customer,
      siteId: "SITE-DEMO-02",
      opportunityType: null,
      recommendedAction: "Update missing data",
      priority: "Medium",
      priorityScore: 62,
      risk: "Low",
      confidence: "High confidence (demo)",
      estimatedDemoRevenueImpact: "—",
      estimatedDemoRevenueAtRisk: "Quote blocked (demo)",
      evidence: [{ id: "ev4", source: "Data quality", summary: "MPAN missing", module: "Quotes", demonstration: true }],
      explanation: "Missing MPAN rule (demo).",
      owner: "Platform (demo)",
      dueDate: "2026-07-30",
      dueDateLabel: "30 Jul 2026",
      humanApprovalRequired: false,
      sourceEvents: ["Meter information incomplete"],
      status: "New",
    }),
    rec({
      id: "REC-DEMO-005",
      title: "Escalate live transfer",
      description: "Wait time exceeded (demo).",
      businessArea: "Operations",
      recordType: "Transfer",
      recordId: "XFR-DEMO-2201",
      customerId: null,
      siteId: null,
      opportunityType: "Lead conversion",
      recommendedAction: "Assign agent",
      priority: "Critical",
      priorityScore: 88,
      risk: "High",
      confidence: "High confidence (demo)",
      estimatedDemoRevenueImpact: "£15k lead (demo)",
      estimatedDemoRevenueAtRisk: "Lead loss (demo)",
      evidence: [{ id: "ev5", source: "Live transfer queue", summary: "Wait 195s", module: "Live Transfers", demonstration: true }],
      explanation: "Transfer wait threshold (demo).",
      owner: "Jordan Lee (demo)",
      dueDate: "2026-07-28",
      dueDateLabel: "28 Jul 2026",
      humanApprovalRequired: false,
      sourceEvents: ["Transfer waiting"],
      status: "New",
    }),
    rec({
      id: "REC-DEMO-006",
      title: "Request latest bill",
      description: "Validate consumption before tender (demo).",
      businessArea: "Customer",
      recordType: "Customer",
      recordId: customer,
      customerId: customer,
      siteId: null,
      opportunityType: null,
      recommendedAction: "Request bill",
      priority: "Medium",
      priorityScore: 58,
      risk: "Low",
      confidence: "Medium confidence (demo)",
      estimatedDemoRevenueImpact: "—",
      estimatedDemoRevenueAtRisk: "Pricing accuracy (demo)",
      evidence: [{ id: "ev6", source: "Data quality", summary: "Bill age > 90d", module: "Customer 360", demonstration: true }],
      explanation: "Data completeness rule (demo).",
      owner: "Alex Morgan (demo)",
      dueDate: "2026-07-31",
      dueDateLabel: "31 Jul 2026",
      humanApprovalRequired: false,
      sourceEvents: ["Customer information incomplete"],
      status: "New",
    }),
    rec({
      id: "REC-DEMO-007",
      title: "Review quote margin",
      description: "Margin outside demo band (demo).",
      businessArea: "Sales",
      recordType: "Quote",
      recordId: "QTE-2026-0147",
      customerId: customer,
      siteId: null,
      opportunityType: "Quote conversion",
      recommendedAction: "Review quote",
      priority: "High",
      priorityScore: 74,
      risk: "Medium",
      confidence: "High confidence (demo)",
      estimatedDemoRevenueImpact: "£85k quote (demo)",
      estimatedDemoRevenueAtRisk: "Margin erosion (demo)",
      evidence: [{ id: "ev7", source: "Quote desk", summary: "Margin 18.5%", module: "Quotes", demonstration: true }],
      explanation: "Quote margin review rule S-7 (demo).",
      owner: "Sam Patel (demo)",
      dueDate: "2026-07-28",
      dueDateLabel: "28 Jul 2026",
      humanApprovalRequired: true,
      sourceEvents: ["Quote reviewed"],
      status: "Under review",
    }),
  ];
}

export function getDemoPriorityQueue(): Recommendation[] {
  const ctx: DecisionContext = {
    customerId: "CUST-DEMO-001",
    contractEndDays: 0,
    annualValueGbp: 109000,
    daysSinceContact: 31,
    outstandingCommissionGbp: 8200,
    missingMpan: true,
    liveTransferWaitSec: 195,
  };
  const rows = buildRecommendationsFromContext(ctx, 92, true);
  return [...rows].sort((a, b) => b.priorityScore - a.priorityScore);
}

export { RULE_VERSION, CONTEXT_VERSION };
