import type { DecisionRule } from "./types";

export const DECISION_RULE_LIBRARY: DecisionRule[] = [
  { id: "S-01", name: "High-value lead requiring immediate contact", businessArea: "Sales", description: "Lead ACV above threshold with no recent contact.", triggerHint: "Lead created / assigned" },
  { id: "S-02", name: "Lead inactive too long", businessArea: "Sales", description: "No activity beyond inactivity threshold.", triggerHint: "Lead inactive" },
  { id: "S-03", name: "Lead ready for quote", businessArea: "Sales", description: "Qualification complete with consumption data.", triggerHint: "Lead qualified" },
  { id: "S-04", name: "Quote stalled", businessArea: "Sales", description: "Quote age exceeds stall threshold.", triggerHint: "Quote sent" },
  { id: "S-05", name: "Quote close to expiry", businessArea: "Sales", description: "Expiry within warning window.", triggerHint: "Quote expiry proximity" },
  { id: "S-06", name: "Quote likely to win", businessArea: "Sales", description: "Win probability model above band.", triggerHint: "Quote viewed" },
  { id: "S-07", name: "Quote margin review required", businessArea: "Sales", description: "Margin outside demo band.", triggerHint: "Quote reviewed" },
  { id: "C-01", name: "Customer without recent contact", businessArea: "Customer", description: "Days since contact exceeded.", triggerHint: "Customer at risk" },
  { id: "C-02", name: "Customer health deteriorating", businessArea: "Customer", description: "Health score dropped.", triggerHint: "Customer updated" },
  { id: "C-03", name: "Customer missing critical data", businessArea: "Customer", description: "Completeness below minimum.", triggerHint: "Data quality" },
  { id: "C-04", name: "Multi-site review opportunity", businessArea: "Customer", description: "Multiple sites without consolidated tender.", triggerHint: "Site created" },
  { id: "C-05", name: "Customer at risk of leaving", businessArea: "Customer", description: "Churn indicators (demo).", triggerHint: "Renewal risk" },
  { id: "R-01", name: "Renewal window opened", businessArea: "Renewals", description: "Contract within renewal window.", triggerHint: "Renewal window opened" },
  { id: "R-02", name: "Renewal contact overdue", businessArea: "Renewals", description: "No contact since window open.", triggerHint: "Renewal task created" },
  { id: "R-03", name: "High-value renewal at risk", businessArea: "Renewals", description: "High ACV with low renewal probability.", triggerHint: "Renewal escalated" },
  { id: "R-04", name: "Renewal likely to retain", businessArea: "Renewals", description: "Probability model favourable.", triggerHint: "Renewal quote created" },
  { id: "R-05", name: "Renewal requires director review", businessArea: "Renewals", description: "Value or risk triggers exec review.", triggerHint: "Renewal escalated" },
  { id: "CT-01", name: "Contract paperwork incomplete", businessArea: "Contracts", description: "Missing LOA or signatures.", triggerHint: "Contract paperwork incomplete" },
  { id: "CT-02", name: "Contract close to start date", businessArea: "Contracts", description: "Start imminent without live status.", triggerHint: "Contract pending signature" },
  { id: "CT-03", name: "Contract rejected", businessArea: "Contracts", description: "Supplier rejection recorded.", triggerHint: "Contract rejected" },
  { id: "CT-04", name: "Contract expired", businessArea: "Contracts", description: "Out of contract.", triggerHint: "Contract expired" },
  { id: "CT-05", name: "Contract renewal handover required", businessArea: "Contracts", description: "Handover to renewals team.", triggerHint: "Contract live" },
  { id: "CM-01", name: "Commission overdue", businessArea: "Commission", description: "Past expected payment date.", triggerHint: "Commission overdue" },
  { id: "CM-02", name: "Commission underpaid", businessArea: "Commission", description: "Variance from forecast.", triggerHint: "Commission underpaid" },
  { id: "CM-03", name: "Commission dispute likely", businessArea: "Commission", description: "Pattern suggests dispute.", triggerHint: "Commission disputed" },
  { id: "CM-04", name: "Supplier payment deterioration", businessArea: "Commission", description: "Delays increasing.", triggerHint: "Supplier payment delayed" },
  { id: "CM-05", name: "High-value recovery opportunity", businessArea: "Commission", description: "Large outstanding balance.", triggerHint: "Commission expected" },
  { id: "SP-01", name: "Supplier acceptance declining", businessArea: "Suppliers", description: "Acceptance rate trend down.", triggerHint: "Supplier performance changed" },
  { id: "SP-02", name: "Supplier payment speed declining", businessArea: "Suppliers", description: "Slower payments.", triggerHint: "Supplier payment delayed" },
  { id: "SP-03", name: "Supplier service issue increasing", businessArea: "Suppliers", description: "Service tickets up.", triggerHint: "Supplier service issue created" },
  { id: "SP-04", name: "Supplier no longer suitable for sector", businessArea: "Suppliers", description: "Appetite mismatch.", triggerHint: "Supplier appetite changed" },
  { id: "SP-05", name: "Preferred supplier opportunity", businessArea: "Suppliers", description: "Better fit available.", triggerHint: "Supplier recommendation updated" },
  { id: "O-01", name: "Live transfer waiting too long", businessArea: "Operations", description: "Wait exceeds threshold.", triggerHint: "Transfer waiting" },
  { id: "O-02", name: "Account manager overloaded", businessArea: "Operations", description: "Open tasks above cap.", triggerHint: "Task assigned" },
  { id: "O-03", name: "Overdue task escalation", businessArea: "Operations", description: "Tasks past due.", triggerHint: "Task overdue" },
  { id: "O-04", name: "Data-quality issue affecting revenue", businessArea: "Operations", description: "Missing fields block revenue.", triggerHint: "Missing data" },
  { id: "O-05", name: "Approval queue ageing", businessArea: "Operations", description: "Approvals pending too long.", triggerHint: "Waiting for approval" },
  { id: "G-01", name: "Solar opportunity", businessArea: "Growth", description: "Solar suitability placeholder.", triggerHint: "Consumption updated" },
  { id: "G-02", name: "Battery opportunity", businessArea: "Growth", description: "Battery suitability placeholder.", triggerHint: "Site updated" },
  { id: "G-03", name: "EV opportunity", businessArea: "Growth", description: "EV suitability placeholder.", triggerHint: "Customer updated" },
  { id: "G-04", name: "Water opportunity", businessArea: "Growth", description: "Cross-sell water (demo).", triggerHint: "Customer created" },
  { id: "G-05", name: "Telecoms opportunity", businessArea: "Growth", description: "Cross-sell telecoms (demo).", triggerHint: "Customer created" },
  { id: "G-06", name: "Merchant services opportunity", businessArea: "Growth", description: "Cross-sell merchant (demo).", triggerHint: "Quote accepted" },
  { id: "G-07", name: "Insurance opportunity", businessArea: "Growth", description: "Cross-sell insurance (demo).", triggerHint: "Contract live" },
  { id: "G-08", name: "Metering review opportunity", businessArea: "Growth", description: "Metering review (demo).", triggerHint: "Meter information incomplete" },
  { id: "G-09", name: "kVA review opportunity", businessArea: "Growth", description: "kVA review placeholder.", triggerHint: "Consumption updated" },
  { id: "G-10", name: "MOP review opportunity", businessArea: "Growth", description: "MOP review placeholder.", triggerHint: "Site updated" },
  { id: "G-11", name: "DC review opportunity", businessArea: "Growth", description: "DC review placeholder.", triggerHint: "Contract live" },
];
