import type { ConfidenceResult, EvidenceItem } from "./types";

/**
 * The single confidence rule used everywhere in this engine. Confidence is
 * purely a function of how much of the relevant evidence was genuinely
 * available — never an arbitrary number, never generated by a model. This
 * file is the one place that rule lives, so it can't drift between
 * capabilities.
 */
export function calculateConfidence(evidence: EvidenceItem[]): ConfidenceResult {
  const total = evidence.length;
  const available = evidence.filter((item) => item.available).length;

  if (total === 0) {
    return {
      level: "Insufficient",
      explanation: "No evidence items were evaluated for this capability.",
      evidenceAvailable: 0,
      evidenceTotal: 0,
    };
  }

  const ratio = available / total;
  const percent = Math.round(ratio * 100);
  const explanation = `${available} of ${total} evidence items available (${percent}%).`;

  if (ratio >= 0.8) {
    return { level: "High", explanation, evidenceAvailable: available, evidenceTotal: total };
  }
  if (ratio >= 0.5) {
    return { level: "Medium", explanation, evidenceAvailable: available, evidenceTotal: total };
  }
  return { level: "Low", explanation, evidenceAvailable: available, evidenceTotal: total };
}
