-- Baseline / prerequisite migration.
--
-- WHY THIS EXISTS: leads, tasks, and activities were created directly in
-- the Supabase SQL editor / dashboard before this project adopted tracked
-- migrations. They predate 20250727180000_customers_and_sites.sql, which
-- already assumes all three exist (it adds a customers.source_lead_id FK
-- to public.leads, and ALTERs public.tasks / public.activities to add a
-- customer_id column). Because no migration ever created the base tables,
-- the migration chain cannot run end-to-end on a fresh/shadow database.
--
-- This migration backfills only the pre-existing shape of the three
-- tables, exactly as captured in supabase/remote_public_schema.sql, MINUS
-- the customer_id columns on tasks/activities (those are added, as
-- before, by 20250727180000_customers_and_sites.sql immediately after).
--
-- Timestamped earlier than 20250727180000 so it runs first in the chain.
--
-- SAFE ON PRODUCTION: every statement is guarded (IF NOT EXISTS / DO
-- blocks), so running this against the existing remote database — where
-- these tables already exist — is a documented no-op. It is intended for
-- fresh/shadow databases; do not treat its presence as a signal to run
-- `supabase db push` here (see docs/RELEASE_CHECKLIST.md / repo rules on
-- remote changes).

create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  company_name text,
  contact_name text,
  telephone text,
  email text,
  supplier text,
  contract_end date,
  status text,
  notes text
);

create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  lead_id bigint,
  title text,
  due_date date,
  due_time time without time zone,
  priority text,
  status text,
  notes text
);

create table if not exists public.activities (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  lead_id bigint,
  activity_type text,
  title text,
  details text,
  activity_date date,
  activity_time time without time zone
);
