import type { DemoAiContractRecommendation, DemoContractRecord } from "./types";

function detail(partial: Partial<DemoContractRecord["detail"]> = {}): DemoContractRecord["detail"] {
  return {
    mpanMprn: "00 123 456 789 012 (demo)",
    meterSerial: "E-884422 (demo)",
    contractLength: "36 months (demo)",
    unitRate: "14.2p/kWh (demo)",
    standingCharge: "£0.45/day (demo)",
    contractNotes: "Demo contract notes — not live CRM data.",
    previousSupplier: "Incumbent Energy (demo)",
    previousContract: "Fixed 24-month ending 2023 (demo)",
    renewalHistory: ["2023 renewal — demo", "2020 renewal — demo"],
    ...partial,
  };
}

export function getDemoContractRecords(): DemoContractRecord[] {
  return [
    {
      id: "c-001",
      customer: "Derby Manufacturing Ltd",
      customerId: 1,
      site: "Riverside Industrial Estate",
      supplier: "EDF Energy (demo)",
      fuelType: "Dual",
      contractType: "Fixed",
      startDate: "2023-08-01",
      endDate: "2026-07-28",
      status: "Renewal due",
      accountManager: "Alex Morgan (demo)",
      annualConsumption: "600,000 kWh (demo)",
      estimatedAnnualSpend: "£109,800 (demo)",
      demoCommission: "£4,860 (demo)",
      riskLevel: "Critical",
      recommendedAction: "Contact customer now (demo)",
      region: "East Midlands",
      renewalMonth: "Jul 2026",
      detail: detail({ contractNotes: "End date aligns with demo as-of date — renewal due." }),
    },
    {
      id: "c-002",
      customer: "Peak Logistics Group",
      customerId: null,
      site: "M1 Hub",
      supplier: "Opus Energy (demo)",
      fuelType: "Electricity",
      contractType: "Fixed",
      startDate: "2024-01-15",
      endDate: "2026-08-15",
      status: "Live",
      accountManager: "Jordan Lee (demo)",
      annualConsumption: "320,000 kWh (demo)",
      estimatedAnnualSpend: "£68,400 (demo)",
      demoCommission: "£2,120 (demo)",
      riskLevel: "High",
      recommendedAction: "Begin tender process (demo)",
      region: "East Midlands",
      renewalMonth: "Aug 2026",
      detail: detail(),
    },
    {
      id: "c-003",
      customer: "Harbor Foods Ltd",
      customerId: null,
      site: "Cold Store A",
      supplier: "British Gas Lite (demo)",
      fuelType: "Gas",
      contractType: "Fixed",
      startDate: "2025-03-01",
      endDate: "2026-09-30",
      status: "Live",
      accountManager: "Alex Morgan (demo)",
      annualConsumption: "180,000 kWh (demo)",
      estimatedAnnualSpend: "£32,100 (demo)",
      demoCommission: "£960 (demo)",
      riskLevel: "Medium",
      recommendedAction: "Review consumption (demo)",
      region: "Yorkshire",
      renewalMonth: "Sep 2026",
      detail: detail({ mpanMprn: "MPRN 1234567890 (demo)" }),
    },
    {
      id: "c-004",
      customer: "Summit Print Co",
      customerId: null,
      site: "City Works",
      supplier: "SmartestEnergy (demo)",
      fuelType: "Electricity",
      contractType: "Flexible",
      startDate: "2026-07-01",
      endDate: "2029-06-30",
      status: "Live",
      accountManager: "Sam Patel (demo)",
      annualConsumption: "95,000 kWh (demo)",
      estimatedAnnualSpend: "£21,500 (demo)",
      demoCommission: "£645 (demo)",
      riskLevel: "Low",
      recommendedAction: "Monitor — no action (demo)",
      region: "North West",
      renewalMonth: "Jun 2029",
      detail: detail(),
    },
    {
      id: "c-005",
      customer: "Northbridge Care",
      customerId: null,
      site: "Main Campus",
      supplier: "EDF Energy (demo)",
      fuelType: "Dual",
      contractType: "Fixed",
      startDate: "2026-07-10",
      endDate: "2029-07-09",
      status: "Live",
      accountManager: "Jordan Lee (demo)",
      annualConsumption: "410,000 kWh (demo)",
      estimatedAnnualSpend: "£88,200 (demo)",
      demoCommission: "£3,960 (demo)",
      riskLevel: "Low",
      recommendedAction: "Signed this month — onboarding (demo)",
      region: "South East",
      renewalMonth: "Jul 2029",
      detail: detail(),
    },
    {
      id: "c-006",
      customer: "Atlas Metals",
      customerId: null,
      site: "Forge Lane",
      supplier: "Opus Energy (demo)",
      fuelType: "Electricity",
      contractType: "Fixed",
      startDate: "2024-06-01",
      endDate: "2026-06-30",
      status: "Expired",
      accountManager: "Alex Morgan (demo)",
      annualConsumption: "250,000 kWh (demo)",
      estimatedAnnualSpend: "£54,000 (demo)",
      demoCommission: "£0 (demo)",
      riskLevel: "Critical",
      recommendedAction: "Out of contract — urgent (demo)",
      region: "West Midlands",
      renewalMonth: "Jun 2026",
      detail: detail(),
    },
    {
      id: "c-007",
      customer: "Greenleaf Hotels",
      customerId: null,
      site: "Central Property",
      supplier: "British Gas Lite (demo)",
      fuelType: "Gas",
      contractType: "Fixed",
      startDate: "2023-01-01",
      endDate: "2025-12-31",
      status: "Lost",
      accountManager: "Sam Patel (demo)",
      annualConsumption: "140,000 kWh (demo)",
      estimatedAnnualSpend: "£28,000 (demo)",
      demoCommission: "£0 (demo)",
      riskLevel: "High",
      recommendedAction: "Lost to competitor (demo)",
      region: "London",
      renewalMonth: "Dec 2025",
      detail: detail(),
    },
    {
      id: "c-008",
      customer: "Civic Workspace Ltd",
      customerId: null,
      site: "Block B",
      supplier: "EDF Energy (demo)",
      fuelType: "Electricity",
      contractType: "Fixed",
      startDate: "2026-07-20",
      endDate: "2028-07-19",
      status: "Pending signature",
      accountManager: "Jordan Lee (demo)",
      annualConsumption: "72,000 kWh (demo)",
      estimatedAnnualSpend: "£16,800 (demo)",
      demoCommission: "£504 (demo)",
      riskLevel: "Medium",
      recommendedAction: "Missing paperwork (demo)",
      region: "South West",
      renewalMonth: "Jul 2028",
      detail: detail({ contractNotes: "Awaiting LOA — demo status." }),
    },
    {
      id: "c-009",
      customer: "Meridian Labs",
      customerId: null,
      site: "Science Park",
      supplier: "SmartestEnergy (demo)",
      fuelType: "Dual",
      contractType: "Fixed",
      startDate: "2025-11-01",
      endDate: "2026-10-31",
      status: "Live",
      accountManager: "Alex Morgan (demo)",
      annualConsumption: "520,000 kWh (demo)",
      estimatedAnnualSpend: "£102,400 (demo)",
      demoCommission: "£3,580 (demo)",
      riskLevel: "Medium",
      recommendedAction: "Early renewal opportunity (demo)",
      region: "East of England",
      renewalMonth: "Oct 2026",
      detail: detail(),
    },
    {
      id: "c-010",
      customer: "Oakwood Estates",
      customerId: null,
      site: "Retail Parade",
      supplier: "Opus Energy (demo)",
      fuelType: "Gas",
      contractType: "Fixed",
      startDate: "2026-05-01",
      endDate: "2026-07-15",
      status: "Renewal due",
      accountManager: "Sam Patel (demo)",
      annualConsumption: "88,000 kWh (demo)",
      estimatedAnnualSpend: "£17,200 (demo)",
      demoCommission: "£516 (demo)",
      riskLevel: "Critical",
      recommendedAction: "Supplier negotiation advised (demo)",
      region: "North West",
      renewalMonth: "Jul 2026",
      detail: detail(),
    },
    {
      id: "c-011",
      customer: "Beacon Health Trust",
      customerId: null,
      site: "District Hospital",
      supplier: "EDF Energy (demo)",
      fuelType: "Electricity",
      contractType: "Fixed",
      startDate: "2026-06-15",
      endDate: "2026-08-27",
      status: "Submitted",
      accountManager: "Jordan Lee (demo)",
      annualConsumption: "680,000 kWh (demo)",
      estimatedAnnualSpend: "£142,000 (demo)",
      demoCommission: "£5,960 (demo)",
      riskLevel: "High",
      recommendedAction: "Commission review required (demo)",
      region: "South East",
      renewalMonth: "Aug 2026",
      detail: detail(),
    },
    {
      id: "c-012",
      customer: "Riverdale Schools",
      customerId: null,
      site: "Academy Campus",
      supplier: "British Gas Lite (demo)",
      fuelType: "Gas",
      contractType: "Fixed",
      startDate: "2026-02-01",
      endDate: "2026-07-28",
      status: "Live",
      accountManager: "Alex Morgan (demo)",
      annualConsumption: "120,000 kWh (demo)",
      estimatedAnnualSpend: "£24,600 (demo)",
      demoCommission: "£738 (demo)",
      riskLevel: "Critical",
      recommendedAction: "Due today — contact customer (demo)",
      region: "Yorkshire",
      renewalMonth: "Jul 2026",
      detail: detail(),
    },
    {
      id: "c-013",
      customer: "Draft Holdings Ltd",
      customerId: null,
      site: "Head Office",
      supplier: "SmartestEnergy (demo)",
      fuelType: "Electricity",
      contractType: "Fixed",
      startDate: "2026-08-01",
      endDate: "2029-07-31",
      status: "Draft",
      accountManager: "Sam Patel (demo)",
      annualConsumption: "45,000 kWh (demo)",
      estimatedAnnualSpend: "£10,200 (demo)",
      demoCommission: "£306 (demo)",
      riskLevel: "Low",
      recommendedAction: "Complete draft (demo)",
      region: "London",
      renewalMonth: "Jul 2029",
      detail: detail({ contractNotes: "Draft — not submitted." }),
    },
    {
      id: "c-014",
      customer: "Closed Unit Co",
      customerId: null,
      site: "Warehouse 3",
      supplier: "Opus Energy (demo)",
      fuelType: "Electricity",
      contractType: "Fixed",
      startDate: "2022-01-01",
      endDate: "2025-01-01",
      status: "Terminated",
      accountManager: "Jordan Lee (demo)",
      annualConsumption: "— (demo)",
      estimatedAnnualSpend: "£0 (demo)",
      demoCommission: "£0 (demo)",
      riskLevel: "Medium",
      recommendedAction: "Archived site (demo)",
      region: "West Midlands",
      renewalMonth: "Jan 2025",
      detail: detail(),
    },
  ];
}

export function getDemoContractAiRecommendations(): DemoAiContractRecommendation[] {
  return [
    {
      id: "ai-c-1",
      type: "Contact customer now",
      detail: "Derby Manufacturing — contract end 28 Jul 2026 (demo).",
      contractId: "c-001",
    },
    {
      id: "ai-c-2",
      type: "Begin tender process",
      detail: "Peak Logistics — 19 days to end in demo register.",
      contractId: "c-002",
    },
    {
      id: "ai-c-3",
      type: "Check meter data",
      detail: "Harbor Foods — gas AQ variance flagged (demo).",
      contractId: "c-003",
    },
    {
      id: "ai-c-4",
      type: "Missing paperwork",
      detail: "Civic Workspace — pending signature (demo).",
      contractId: "c-008",
    },
    {
      id: "ai-c-5",
      type: "Customer at risk",
      detail: "Atlas Metals — expired without renewal (demo).",
      contractId: "c-006",
    },
  ];
}
